//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "flow_instance_billing")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub flow_instance_id: Uuid,
    pub cpu: i32,
    pub memory: i64,
    pub storage: i64,
    pub wall_time: i64,
    #[sea_orm(column_type = "Decimal(Some((12, 2)))")]
    pub total_price: Decimal,
    pub user_id: Option<Uuid>,
    pub created_time: DateTimeWithTimeZone,
    pub modified_time: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
