//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "queue_bill_config")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub queue_id: Uuid,
    #[sea_orm(column_type = "Decimal(Some((20, 10)))")]
    pub cpu: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 10)))")]
    pub memory: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 10)))")]
    pub storage: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 10)))")]
    pub cpu_time: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 10)))")]
    pub wall_time: Decimal,
    pub formula: String,
    pub created_time: DateTimeWithTimeZone,
    pub modified_time: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::queue::Entity",
        from = "Column::QueueId",
        to = "super::queue::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Queue,
}

impl Related<super::queue::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Queue.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
